language: node_js
script:
  - "node_modules/karma/bin/karma start karma.conf.js --single-run --browsers PhantomJS"

node_js:
  - "0.10"
  
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  